---
- hosts: localhost
  tasks:
  - name: Save ansible timestamp
    copy:
      src: "files/ansible_timestamp"
      dest: "/opt/ansible_timestamp"
      owner: root
      group: root



  - name: HACK to fix IP addresses 
    copy:
      src: "files/post_setup_ansible
      dest: "/root/setup_ansible
      owner: root
      group: root
      mode: 0755

  - name: HACK to run fix IP script at boot
    command:
      cmd: systemctl enable setup_ansible
    







  # This must be last (you know, since it reboots)
  - name: Post-install reboot
    shell: "sleep 5 && reboot"
    when: need_reboot is defined
