---
- hosts: localhost
  tasks:

  - name: Install Dependencies (Apt)
    apt:
      pkg:
          - libhdf5-dev
          - docker.io
          - mosquitto-clients 
          - host
          - dnsutils
          - screen
          - telnet
          - chrony
          - telegraf
          - influxdb
          - influxdb-client
          - vim
          - less
          - file
          - telnet
          - iptables
          - python3-pip
          - xrdp
          - cmake
          - xorg-dev
          - boost-all-dev
          - minicom
          - net-tools
          - iftop
      state: present
      update_cache: yes



  - name: Install Digital RF (Pip)
    pip:
      name:
        - jetson-stats