---
- hosts: localhost
  tasks:

  - name: Get GPG key for kitware repo (for cmake)
    shell:  wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null


  - name: Add deadsnakes PPA
    apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Python 3.13
    apt:
      name: python3.13
      state: present

  - name: Install Dependencies (Apt)
    apt:
      pkg:
          - libhdf5-dev
          - docker.io
          - mosquitto-clients 
          - host
          - dnsutils
          - screen
          - telnet
          - chrony
          - telegraf
          - influxdb
          - influxdb-client
          - vim
          - nano
          - less
          - file
          - telnet
          - iptables
          - python3-pip
          - cmake
          - xorg-dev
          - libboost-all-dev
          - minicom
          - net-tools
          - iftop
          - backport-iwlwifi-dkms
          - firefox
          - cuda-nvtx-12-2 
          - libcufft-dev-12-2 
          - libcusolver-dev-12-2 
          - libcurand-dev-12-2
          - holoscan
          - libpcap0.8-dev 
          - meson 
          - python3-pyelftools
      state: present
      update_cache: yes


  - name: Remove gnome-initial-setup
    apt:
      pkg:
        - gnome-initial-setup
      state: absent

  # - name: Install Utilities (Pip)
  #   pip:
  #     name:
  #       - jetson-stats
  #   async: 120
  #   poll: 5
  #   register: jetson_stats_watcher

  # - name: Check jetson-stats install
  #   async_status:
  #     jid: "{{ jetson_stats_watcher.ansible_job_id }}"
  #   register: jetson_stats_result
  #   until: jeton_status_result.finished
  #   retries: 60  # Adjust based on your needs
  #   delay: 10
  #   failed_when: jetson_status_result.rc is not defined and retries == 60

  # - name: Handle jetson-stats timeout
  #   command: /usr/sbin/service jtop stop
  #   when: jeton_status_result.rc is not defined


  # - name: Install uv
  #   shell: "files/uv-install.sh"


  - name: Clone holohub repository
    git:
      repo: 'https://github.com/ryanvolz/holohub.git'
      dest: /opt/holohub
      update: yes
      version: "mep"
      accept_hostkey: yes
    register: run_holohub_setup
  
  - name: Add git safe.directory to holohub repo
    shell: GIT_DIR=/opt/holohub/.git GIT_WORK_TREE=/opt/holohub git config --add safe.directory "/opt/holohub"
    when: not run_holohub_setup.before


  - name: Setup holohub
    command:
      cmd: ./run setup
      chdir: /opt/holohub
    when: run_holohub_setup


  - name: Check if dpdk is installed
    ansible.builtin.command:
      cmd: dpkg-query -W -f='${Version}' dpdk-for-jetson
    register: dpdk_check
    ignore_errors: yes

  - name: Download dpdk
    ansible.builtin.command:
      cmd: wget https://github.com/spectrumx/ansible/releases/download/deps-20241112/dpdk-for-jetson_22.11.6-1ubuntu2_arm64.deb -O /tmp/dpdk-for-jetson_22.11.6-1ubuntu2_arm64.deb
      warn: false
    when: dpdk_check.stdout != "22.11.6-1ubuntu2"

  - name: Install dpdk
    apt:
      deb: /tmp/dpdk-for-jetson_22.11.6-1ubuntu2_arm64.deb
      state: present
    when: dpdk_check.stdout != "22.11.6-1ubuntu2"

  - name: Install holohub (long)
    command:
      cmd: './run build mimo_radar_pipeline --configure-args "-DMATX_EN_PYBIND11=ON -DPYBIND11_FINDPYTHON=ON -DPython_EXECUTABLE=/usr/bin/python3 -DPython_ROOT_DIR=/usr/lib/python3"'
      chdir: /opt/holohub
    when: run_holohub_setup

  - name: Holohub setcap
    command:
      cmd: 'setcap cap_net_raw,cap_dac_override,cap_dac_read_search,cap_ipc_lock,cap_sys_admin+ep ./build/applications/mimo_radar_pipeline/cpp/mimo_radar_pipeline'
      chdir: /opt/holohub
    when: run_holohub_setup


