---
- hosts: localhost
  tasks:

  - name: Install GPS Server
    apt:
      pkg:
          - gpsd
          - gpsd-clients
      state: present
      update_cache: no

  # - name: Copy dhcpd.conf
  #   copy:
  #     src: "files/dhcpd.conf"
  #     dest: /etc/dhcp/dhcpd.conf
  #     owner: root
  #     group: root
  #   notify: 
  #     - restart dhcpd




  # handlers:
  #   - name: restart dhcpd
  #     systemd:
  #       name: isc-dhcp-server
  #       state: restarted
  #       enabled: yes
