---
- hosts: localhost
  tasks:

  - name: Get new hostname
    shell: cat /sys/class/net/$(ls /sys/class/net | grep -E '^e' | head -n 1)/address | sed -e 's/://g' | cut -c 9-12
    register: new_hostname
    changed_when: False

  - name: Update hostname (systemd)
    hostname:
      name: "{{ new_hostname.stdout }}"

  - copy: content="{{ new_hostname.stdout }}" dest=/etc/hostname




  - name: Add MASQUERADE rule to POSTROUTING chain
    iptables:
      table: nat
      chain: POSTROUTING
      out_interface: eth0
      jump: MASQUERADE
    notify: Save iptables

  - name: Add FORWARD rule for RELATED,ESTABLISHED state
    iptables:
      chain: FORWARD
      in_interface: eth0
      out_interface: eth1
      match: state
      ctstate: RELATED,ESTABLISHED
      jump: ACCEPT
    notify: Save iptables

  - name: Add FORWARD rule to allow traffic from eth1 to eth0
    iptables:
      chain: FORWARD
      in_interface: eth1
      out_interface: eth0
      jump: ACCEPT
    notify: Save iptables

  - name: Ensure sysctl.conf has the correct values
    lineinfile:
      path: /etc/sysctl.conf
      state: present
      regexp: '^{{ item.key }}'
      line: '{{ item.key }}={{ item.value }}'
    loop:
      - { key: 'net.core.rmem_default', value: '26214400' }
      - { key: 'net.core.rmem_max', value: '104857600' }
      - { key: 'net.core.wmem_default', value: '65536' }
      - { key: 'net.core.wmem_max', value: '104857600' }

  - name: Apply sysctl settings
    command: sysctl -p

  - name: Set ethtool ring buffer sizes
    command: ethtool -G eth2 rx 8192 tx 8192
    ignore_errors: yes

  - name: Set MTU to 9000 on eth2
    command:
      cmd: ip link set dev eth2 mtu 9000
    ignore_errors: yes
    notify:
      - Restart networking

  - name: Check if eth1 has the IP address 192.168.20.1
    command:
      cmd: ip addr show dev eth1
    ignore_errors: yes
    register: eth1_output

  - name: Add IP address to eth1 if not present
    command:
      cmd: ip addr add 192.168.20.1/24 dev eth1
    when: "'192.168.20.1' not in eth1_output.stdout"
    ignore_errors: yes
    notify:
      - Restart networking

  - name: Check if eth2 has the IP address 192.168.20.1
    command:
      cmd: ip addr show dev eth2
    ignore_errors: yes
    register: eth2_output

  - name: Set static IP on eth2
    command:
      cmd: ip addr add 192.168.4.1/24 dev eth2
    when: "'192.168.4.1' not in eth2_output.stdout"
    ignore_errors: yes
    notify:
      - Restart networking

  - name: Append kernel boot args
    ansible.builtin.lineinfile:
      path: /boot/extlinux/extlinux.conf
      regexp: '^APPEND'
      line: '\g<0> isolcpus=0-1 nohz_full=0-1 irqaffinity=2-N rcu_nocbs=0-1 rcu_nocb_poll tsc=reliable audit=0 nosoftlockup default_hugepagesz=1G hugepagesz=1G hugepages=2'
      backrefs: yes





  handlers:
    - name: Save iptables
      command: /sbin/service iptables save
      when: ansible_os_family == "RedHat"

    - name: Save iptables
      command: /sbin/iptables-save
      when: ansible_os_family == "Debian"

    - name: Restart networking
      ansible.builtin.service:
        name: NetworkManager
        state: restarted