---
- hosts: localhost
  tasks:

  - name: Get new hostname
    shell: cat /sys/class/net/$(ls /sys/class/net | grep -E '^e' | head -n 1)/address | sed -e 's/://g' | cut -c 9-12
    register: new_hostname
    changed_when: False

  - name: Update hostname (systemd)
    hostname:
      name: "{{ new_hostname.stdout }}"

  - copy: content="{{ new_hostname.stdout }}" dest=/etc/hostname




  - name: Add MASQUERADE rule to POSTROUTING chain
    iptables:
      table: nat
      chain: POSTROUTING
      out_interface: eth0
      jump: MASQUERADE
    notify: Save iptables

  - name: Add FORWARD rule for RELATED,ESTABLISHED state
    iptables:
      chain: FORWARD
      in_interface: eth0
      out_interface: eth1
      match: state
      ctstate: RELATED,ESTABLISHED
      jump: ACCEPT
    notify: Save iptables

  - name: Add FORWARD rule to allow traffic from eth1 to eth0
    iptables:
      chain: FORWARD
      in_interface: eth1
      out_interface: eth0
      jump: ACCEPT
    notify: Save iptables

  - name: Ensure sysctl.conf has the correct values
    lineinfile:
      path: /etc/sysctl.conf
      state: present
      regexp: '^{{ item.key }}'
      line: '{{ item.key }}={{ item.value }}'
    loop:
      - { key: 'net.core.rmem_default', value: '26214400' }
      - { key: 'net.core.rmem_max', value: '104857600' }
      - { key: 'net.core.wmem_default', value: '65536' }
      - { key: 'net.core.wmem_max', value: '104857600' }

  - name: Apply sysctl settings
    command: sysctl -p

  - name: Set ethtool ring buffer sizes
    command: ethtool -G eth2 rx 8192 tx 8192
    ignore_errors: yes








  handlers:
    - name: Save iptables
      command: /sbin/service iptables save
      when: ansible_os_family == "RedHat"

    - name: Save iptables
      command: /sbin/iptables-save
      when: ansible_os_family == "Debian"