---
- hosts: localhost  
  tasks:

    - name: Add mep user
      user:
        name: mep
        comment: MEP User Account
        groups: "admin"
        shell: /bin/bash
        append: yes

    - name: create mep .ssh directory
      file:
        path: /home/mep/.ssh
        state: directory
        owner: mep
        group: mep
        mode: 0700

    - name: copy ssh key to mep
      copy:
        src: /opt/radiohound/.ssh/mep_key
        dest: /home/mep/.ssh/id_rsa
        mode: 0600
        owner: mep
        group: mep

    - name: copy authorized_keys to mep
      copy:
        src: "files/mep_authorized_keys"
        dest: /home/mep/.ssh/authorized_keys
        mode: 0600
        owner: mep
        group: mep


    - name: Create /data for ring buffers
      file:
        path: /data
        state: directory
        owner: mep
        group: mep
        mode: 777

    - name: Add user to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%ADMIN ALL='
        line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s