---
- hosts: localhost  
  tasks:

    - name: Add mep user
      user:
        name: mep
        comment: MEP User Account
        groups: "i2c"
        shell: /bin/bash

    - name: create icarus' .ssh directory
      file:
        path: /home/mep/.ssh
        state: directory
        owner: mep
        group: mep
        mode: 0700

    - name: copy ssh key to mep
      copy:
        src: /opt/radiohound/.ssh/mep_key
        dest: /home/mep/.ssh/id_rsa
        mode: 0600
        owner: mep
        group: mep

    - name: copy authorized_keys to mep
      copy:
        src: "files/mep_authorized_keys"
        dest: /home/mep/.ssh/authorized_keys
        mode: 0600
        owner: mep
        group: mep
