---
- hosts: localhost
  tasks:

  - name: Check if Intel Wifi repo is cloned
    stat:
      path: /opt/linux-firmware
    register: checkout_intel_wifi

  - name: Clone the Intel 8265 WIFI drivers repository
    git:
      repo: 'https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git'
      dest: /opt/linux-firmware
      update: no
    when: checkout_intel_wifi

  - name: Copy iwl-8265-34 file to /lib/firmware
    copy:
      src: /opt/linux-firmware/iwlwifi-8265-34.ucode
      dest: /lib/firmware/
      mode: '0644'

  - name: Copy iwl-8265-36 file to /lib/firmware
    copy:
      src: /opt/linux-firmware/iwlwifi-8265-36.ucode
      dest: /lib/firmware/
      mode: '0644'

  - name: Create WiFi hotspot connection
    template:
      src: templates/MEP-hotspot.nmconnection.j2
      dest: /etc/NetworkManager/system-connections/MEP-{{ hostname }}.nmconnection
      owner: root
      group: root
      mode: 0600

  - name: Reload NetworkManager configuration
    command: nmcli connection reload
    ignore_errors: yes
